version: '3.8'

services:
  mongodb:
    image: 'mongo:latest'
    container_name: 'mongo-db'
    environment:
      MONGO_INITDB_DATABASE: 'categorie-db'
    ports:
      - '27017:27017'
    networks:
      - mynetwork
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  mynetwork:
    driver: bridge
