services:
  mongodb:
    image: 'mongo:latest'
    container_name: 'mongo-db'
    environment:
      MONGO_INITDB_DATABASE: 'categorie-db'
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'secret'
    ports:
      - '27017:27017'
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
